version: '3.8'

services:
  webapi:
    build: .
    ports:
      - "81:81"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=ReportMicroservice;User Id=sa;Password=YourStrong!Passw0rd;
      - RabbitMQ__HostName=rmq
      - RabbitMQ__Port=5672
      - RabbitMQ__UserName=guest
      - RabbitMQ__Password=guest
    networks:
      - mynetwork
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1434:1434"
    networks:
      - mynetwork

  migrate:
    build: .
    command: ["dotnet", "ef", "database", "update", "--project", "src/reportMicroservice/WebAPI/WebAPI.csproj"]
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=ReportMicroservice;User Id=sa;Password=YourStrong!Passw0rd;
      - RabbitMQ__HostName=rmq
      - RabbitMQ__Port=5672
      - RabbitMQ__UserName=guest
      - RabbitMQ__Password=guest
    networks:
      - mynetwork

networks:
  mynetwork:
    name: mynetwork
    external: true
