version: '3.8'

services:
  webapi:
    build: .
    ports:
      - "81:80"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=ReportMicroservice;User Id=sa;Password=YourStrong!Passw0rd;

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1434:1433"

  migrate:
    build: .
    command: ["dotnet", "ef", "database", "update", "--project", "src/reportMicroservice/WebAPI/WebAPI.csproj"]
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=ReportMicroservice;User Id=sa;Password=YourStrong!Passw0rd;
